<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite name="SeleniumFinal.TekArchSeleniumExam.AutomationScripts" tests="5" time="0.018" ignored="0" failures="0" timestamp="18 Dec 2017 20:55:53 GMT" skipped="0" hostname="edas-MacBook-Air.local" errors="1">
  <testcase name="Login_Error_Message" time="0.001" classname="SeleniumFinal.TekArchSeleniumExam.AutomationScripts"/>
  <testcase name="Demo3" time="0.001" classname="SeleniumFinal.TekArchSeleniumExam.AutomationScripts"/>
  <testcase name="Demo1" time="0.014" classname="SeleniumFinal.TekArchSeleniumExam.AutomationScripts"/>
  <testcase name="Login_To_SalesForce" time="0.001" classname="SeleniumFinal.TekArchSeleniumExam.AutomationScripts">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at SeleniumFinal.TekArchSeleniumExam.AutomationScripts.Login_To_SalesForce(AutomationScripts.java:19)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- Login_To_SalesForce -->
  <testcase name="Demo2" time="0.001" classname="SeleniumFinal.TekArchSeleniumExam.AutomationScripts"/>
</testsuite> <!-- SeleniumFinal.TekArchSeleniumExam.AutomationScripts -->
